import './globals.css';
export const metadata = { title: 'Clinical Evidence Explorer', description: 'Generated by the Clinical Research Compiler' };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (<html lang="en"><body>{children}</body></html>);
}
